### ISSUE TITLE
how can i serialize Transaction object

### ISSUE THREAD

**Issue by SalletOne** [terra-money/terra.kt#2]
now i hava Transaction object， i want to serialize it, how to do?

**Comment by jdekim43** [comment]
Do you need this?
```kotlin
import kotlinx.serialization.encodeToString
import money.terra.amino.AminoFormat
import money.terra.message.SendMessage
import money.terra.model.Coin
import money.terra.model.Transaction
import money.terra.type.Uint128

val transaction = Transaction(
   messages = listOf(SendMessage(
       fromAddress = "terra1~~~~~",
       toAddress = "terra1~~~~~",
       amount = listOf(Coin("uusd", Uint128("1"))),
   )),
)

val serialized = AminoFormat.encodeToString(transaction)
```

**Comment by SalletOne** [comment]
> Do you need this?
> 
> ```kotlin
> import kotlinx.serialization.encodeToString
> import money.terra.amino.AminoFormat
> import money.terra.message.SendMessage
> import money.terra.model.Coin
> import money.terra.model.Transaction
> import money.terra.type.Uint128
> 
> val transaction = Transaction(
>    messages = listOf(SendMessage(
>        fromAddress = "terra1~~~~~",
>        toAddress = "terra1~~~~~",
>        amount = listOf(Coin("uusd", Uint128("1"))),
>    )),
> )
> 
> val serialized = AminoFormat.encodeToString(transaction)
> ```

The kotlin interface https://bombay.stakesystems.io/txs requires a very high miner fee, why is the miner fee of the web wallet so low? Can I turn Transaction in kotlin into tx_bytes?

**Comment by SalletOne** [comment]
request：
{"tx":{"msg":[{"type":"bank/MsgSend","value":{"from_address":"terra1vvlfsgd74t5m8u2q326ht3j0e6n4f6vnxl2cj3","to_address":"terra1uv5acl0xnckxd76s630h5erm8l8nuw9hq6gr2s","amount":[{"amount":"100000","denom":"uluna"}]}}],"memo":"","fee":{"gas":"128630","amount":[{"amount":"1457","denom":"uluna"}]},"signatures":[{"signature":"Sj+CzgFx+LUqgJo+hP4+onE+JDQk4dQVPgWZdikCxTheh4y9Cr1aKB51pJE1sMpmB0kfC8Q1BYcgmq7qZyS3ZA==","pub_key":{"value":"Az3bY8meExVKaFCrSPnr849KwO6SK5GV3WCUx6weSZtn","type":"tendermint/PubKeySecp256k1"},"account_number":"494781","sequence":"0"}],"timeout_height":"0"},"mode":"sync"}
response:
{BlockTxBroadcastResult(height=0, txhash='7786FC5B926C05B7A31A52A26F1C2441299DC096811F21D7DDF17FFF82016F4D', raw_log='insufficient fees; got: "1457uluna", required: "24440uaud,24440ucad,16722uchf,124772ucny,115767udkk,16079ueur,14150ugbp,149726uhkd,280413400uidr,1414930uinr,2058080ujpy,22902572ukrw,19295uluna,55520040umnt,160788unok,977588uphp,13095usdr,160788usek,25726usgd,594271uthb,19295uusd"="24440uaud,24440ucad,16722uchf,124772ucny,115767udkk,16079ueur,14150ugbp,149726uhkd,280413400uidr,1414930uinr,2058080ujpy,22902572ukrw,19295uluna,55520040umnt,160788unok,977588uphp,13095usdr,160788usek,25726usgd,594271uthb,19295uusd"(gas) +""(stability): insufficient fee', gas_wanted=128630, gas_used=1009, logs=None, code=13, codespace='sdk', info=None, data=None, timestamp=None)}

How to calculate fee

**Comment by jdekim43** [comment]
If you only want to estimate fee, Maybe TerraLcdClient is useful.
#### Only estimateFee
```kotlin
val client = TerraLcdClient("bombay-12", "https://bombay-lcd.terra.dev")
val estimateFeeResponse = client.transactionApi.estimateFee(messages, senderAddress, senderAccountNumber, senderSequence, feeDenomination gasAdjustment) //coroutine suspend function
val fee = estimateFeeResponse.fee
```

If you want to broadcast a transaction, i recommend below.

#### With FCD
```kotlin
val mnemonic: String = "..."
val terra = Terra.fcd("bombay-12", "https://bombay-fcd.terra.dev")
val wallet: TerraWallet = terra.walletFromMnemonic(mnemonic)
val receiveWallet: TerraWallet = TerraWallet("terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v")
val deferredResult: Deferred<Pair<BroadcastResult, Transaction>> = wallet.broadcast {
    SendMessage(wallet.address, receiveWallet, listOf(Coin(Uint128(1000), "uluna)).withThis()
}
```

#### With LCD
```kotlin
val mnemonic: String = "..."
val gasPricesProvider = StaticGasPricesProvider(mapOf("uluna" to Decimal("0.01")))
val option = AminoTerraOption("bombay-12", "https://bombay-lcd.terra.dev", gasPricesProvider = gasPricesProvider)
val terra = Terra.amino(option)
val wallet: TerraWallet = terra.walletFromMnemonic(mnemonic)
val receiveWallet: TerraWallet = TerraWallet("terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v")
val deferredResult: Deferred<Pair<BroadcastResult, Transaction>> = wallet.broadcast {
    SendMessage(wallet.address, receiveWallet, listOf(Coin(Uint128(1000), "uluna)).withThis()
}
```
